### PR TITLE
build(docker): dockerize back-end app using docker-compose

### PR DESCRIPTION
**Pull request by davipon**

### CODE REVIEW

**Review by AdrieneTZ — COMMENTED** [review]
Just take some notes:
- port number on `Fly.io` must be 8080

**Review by AdrieneTZ — COMMENTED** [review]
In `.gitignore`, you added `.env.prod`. Do we have to add a file called `.env.prod.example`, just like `.env.example`?

**Comment by davipon** [comment]
> In `.gitignore`, you added `.env.prod`. Do we have to add a file called `.env.prod.example`, just like `.env.example`?

I've commented on both `README.md` and `.env.example`, is that OK for you?

**Comment by AdrieneTZ** [comment]
Yes, I opened an issue to remind documenting `.env.prod` in both `README.me` and `.env.example`. (#19 )

**Review by AdrieneTZ — COMMENTED** [review]
Nice

**Review by AdrieneTZ — COMMENTED** [review]
Nice

**Review by AdrieneTZ — APPROVED** [review]
Nice

**Review by AdrieneTZ — APPROVED** [review]

**Review by AdrieneTZ — APPROVED** [review]

**Review by AdrieneTZ — APPROVED** [review]

**Pull request merged**
