### PR TITLE
fix: remove squash_and_merge.jpg:Zone.Identifier (no idea why it exists)

### LINKED ISSUE #24: Clone succeeded, but checkout failed.
When I tried to clone this repo, below error occured:

```bash
error: invalid path 'assets/squash_and_merge.jpg:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Maybe we should remove `assets/squash_and_merge.jpg:Zone.Identifier`.

### PR DESCRIPTION
**Pull request by davipon**
- Remove the `squash_and_merge.jpg:Zone.Identifier`
- fix #24

### CODE REVIEW

**Review by AdrieneTZ — COMMENTED** [review]
I saw someone faced this situation too ([link](https://stackoverflow.com/questions/66702176/error-invalid-path-filepathzone-identifier)).
How about trying the git cli mentioned on the link above?

**Comment by davipon** [comment]
It does solve the problem! Thank you for the solution.
Do you suggest merging this PR or closing it?

**Comment by davipon** [comment]
OK. I tested a little bit, I can switch to a different branch now, but I cannot restore the file.
We'd better merge this PR since the file is not required.

**Comment by AdrieneTZ** [comment]
OK, I'll press approve button.

**Review by AdrieneTZ — APPROVED** [review]
Approve!

**Pull request merged**
